version: '3'
services:
    # # Criação do servidor web
    # nginx:
    #   image: nginx:latest
    #   container_name: sigfto-nginx
    #   ports:
    #     - "8083:80"
    #   volumes:
    #     - "./sigfpto-backend/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    #   networks:
    #     - sig_net

    # Criação do container Laravel
    app:
      build:
        context: ./sigfpto-backend
        dockerfile: Dockerfile-php
      container_name: sigfpto-backend
      user: "${USER_ID}:${GROUP_ID}"
      volumes:
        - "./sigfpto-backend/app:/var/www/html/app"
        - "./sigfpto-backend/config:/var/www/html/config"
        - "./sigfpto-backend/database:/var/www/html/database"
        - "./sigfpto-backend/resources:/var/www/html/resources"
        - "./sigfpto-backend/routes:/var/www/html/routes"
        - "./sigfpto-backend/composer.json:/var/www/html/composer.json"
        - "./sigfpto-backend/composer.lock:/var/www/html/composer.lock"
      environment:
        - "DB_HOST=db_sig"
        - "DB_PORT=3306"
        - "DB_DATABASE=sig_db"
        - "DB_USERNAME=sig@2023"
        - "DB_PASSWORD=sig@120"
      ports:
        - "8000:8000"
      depends_on: 
        - nginx
        - db_sig
      networks:
        - sig_net

    # Criação do docker para o frontend
    frontend:
      build:
        context: ./sigfpto-frontend
        dockerfile: Dockerfile-react
      user: "${USER_ID}:${GROUP_ID}"
      environment:
        - CHOKIDAR_USEPOLLING=true
      container_name: sigfpto-frontend
      volumes:
        - "./sigfpto-frontend/src:/app/src"
      restart: always
      ports:
        - "3000:3000"
      networks:
          - sig_net

    # Criação do banco de dados
    db_sig:
      image: mariadb:10.6
      restart: always
      ports:
        - "3312:3306"
      volumes:
        - "db_data:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      networks:
        - sig_net

volumes:
  db_data:

networks:
  sig_net: