# Define a imagem base
FROM node:16-alpine3.14

# Define o diretório de trabalho dentro do container
WORKDIR /app

COPY . .

# Instala as dependências do projeto
RUN npm install

# Define a porta que o container irá expor
EXPOSE 3000

# Comando padrão que será executado quando o container for iniciado
CMD ["npm", "start"]