# Container do PHP
FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    git \
    libzip-dev \
    unzip \
    libpq-dev \
    && docker-php-ext-install pdo pdo_mysql zip

# Pasta de trabalho
WORKDIR /var/www/html

# Copia o código-fonte do Laravel para dentro do container
COPY . .

# Instala as dependências do Composer
RUN curl -sS https://getcomposer.org/installer | /usr/local/bin/php -- --install-dir=/usr/local/bin --filename=composer
RUN /usr/local/bin/composer install --no-interaction

# Copia o arquivo .env para dentro do container
COPY .env.example .env

COPY vendor /sigfpto-backend/vendor

RUN php artisan key:generate

RUN php artisan config:cache && \
    php artisan route:cache && \
    php artisan view:cache && \
    chown -R www-data:www-data /var/www/html/storage
   

# Expõe a porta do servidor web
EXPOSE 9000

# Inicia o servidor web do PHP
CMD ["php", "artisan", "serve", "--host=0.0.0.0"]